---
- hosts: Ubuntu
    become: true
    tasks:
      - name: Upgrade all installed packages for Ubuntu
        apt:
          name: "*"
          state: latest
          update_cache: yes
          force_apt_get: no
          when: ansible_distribution == "Ubuntu

